# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('ingresos', models.IntegerField()),
                ('pagas_anuales', models.IntegerField()),
                ('otros_ingresos', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
