# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresanombre', models.CharField(max_length=100)),
                ('empresacargo', models.CharField(max_length=100)),
                ('empresaactividad', models.CharField(max_length=100)),
                ('empresaingresos', models.IntegerField()),
                ('empresapagas', models.IntegerField()),
                ('empresaantiguedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('movil', models.IntegerField()),
                ('fechan', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('estadocivil', models.CharField(max_length=100)),
                ('tipoestadocivil', models.CharField(max_length=100)),
                ('nhijos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoempresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresatipo', models.CharField(max_length=50)),
                ('emrpesaajena', models.BooleanField()),
                ('empresatiempo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Empreses',
        ),
    ]
