# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operadora', '0002_auto_20161130_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='anotaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('personales', models.CharField(max_length=500)),
                ('empresa', models.CharField(max_length=500)),
                ('vivienda', models.CharField(max_length=500)),
                ('financieros', models.CharField(max_length=500)),
                ('avalista', models.CharField(max_length=500, null=True)),
                ('destinado', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='coches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('motor', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('antiguedad', models.DateField()),
                ('matricula', models.CharField(max_length=20)),
                ('estadodelvehiculo', models.CharField(max_length=50)),
                ('coche', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='debecredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Titular', 'Titular'), ('Avalista', 'Avalista')], max_length=20)),
                ('porcientoavalista', models.IntegerField()),
                ('importe', models.IntegerField()),
                ('cuota', models.IntegerField()),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='debemoroso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('importe', models.IntegerField()),
                ('quien', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='deberecivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('importe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='debetarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('cuota', models.IntegerField()),
                ('importe', models.IntegerField()),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='juvilacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('importe', models.IntegerField()),
                ('pagas', models.IntegerField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='paro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('desdecuando', models.DateField()),
                ('cobra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='personaanexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('seguridadsocial', models.CharField(choices=[('Propia', 'Propia'), ('Ajena', 'Ajena')], max_length=20)),
                ('siajenatipo', models.CharField(choices=[('Fijo', 'Fijo'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal')], max_length=20)),
                ('siajenatemporal', models.DateField()),
                ('otrosingresos', models.IntegerField()),
                ('otrosingresostexto', models.CharField(max_length=100)),
                ('otrosgastos', models.IntegerField()),
                ('otrosgastostexto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=50)),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigopostal', models.IntegerField()),
                ('valorvivienda', models.IntegerField(null=True)),
                ('valorhipoteca', models.IntegerField(null=True)),
                ('estapagada', models.BooleanField(default=False)),
                ('sinopagadaanos', models.CharField(max_length=10, null=True)),
                ('sinopagadaentidad', models.CharField(max_length=50, null=True)),
                ('sinopagadapagahipoteca', models.IntegerField(null=True)),
                ('librecargos', models.BooleanField(default=False)),
                ('metros', models.IntegerField(null=True)),
                ('porciento', models.IntegerField(null=True)),
                ('valoralquilada', models.IntegerField(null=True)),
                ('pagaalquiler', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tipoempresa',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='empresaingresos',
            new_name='ingresos',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='empresapagas',
            new_name='numexp',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='fechan',
            new_name='fechanacimiento',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nhijos',
            new_name='numerodehijos',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empresaactividad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empresaantiguedad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empresacargo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empresanombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipoestadocivil',
        ),
        migrations.AddField(
            model_name='empresa',
            name='actividad',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='antiguedad',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='avalista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='otrosingresos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='autoriza',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='justificante',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='medio',
            field=models.CharField(choices=[('Television', 'Television'), ('Prensa', 'Prensa'), ('Radio', 'Radio'), ('Operadora', 'Operadora'), ('Publicidad Estatica', 'Publicidad Estatica'), ('Otros', 'Otros')], default='Otros', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='metodopago',
            field=models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('Hal-Cash', 'Hal-Cash')], default='Hal-Cash', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sihijoscuantoscargo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sihijosingreso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sihijosmayores18',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='tieneavalista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipocasado',
            field=models.CharField(choices=[('Separacion de bienes', 'Separacion de bienes'), ('Bienes gananciales', 'Bienes gananciales')], default='Separacion de bienes', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estadocivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Pareja de hecho', 'Pareja de hecho'), ('Casado', 'Casado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
