# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operadora', '0003_auto_20161206_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='medio',
            field=models.CharField(choices=[('Television', 'Television'), ('Prensa', 'Prensa'), ('Radio', 'Radio'), ('Web', 'Web'), ('Publicidad Estatica', 'Publicidad Estatica'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
