# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operadora', '0004_auto_20161206_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='tieneavalista',
            new_name='avalista',
        ),
        migrations.AddField(
            model_name='persona',
            name='numexp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
