# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anotaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('personales', models.CharField(max_length=500, null=True)),
                ('empresa', models.CharField(max_length=500, null=True)),
                ('vivienda', models.CharField(max_length=500, null=True)),
                ('financieros', models.CharField(max_length=500, null=True)),
                ('avalista', models.CharField(max_length=500, null=True)),
                ('destinado', models.CharField(max_length=500, null=True)),
                ('generales', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('motor', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('antiguedad', models.DateField()),
                ('matricula', models.CharField(max_length=20)),
                ('estadodelvehiculo', models.CharField(max_length=50)),
                ('coche', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='debecredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Titular', 'Titular'), ('Avalista', 'Avalista')], max_length=20, null=True)),
                ('porcientoavalista', models.IntegerField(null=True)),
                ('importe', models.IntegerField(null=True)),
                ('cuota', models.IntegerField(null=True)),
                ('entidad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='debemoroso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('importe', models.IntegerField(null=True)),
                ('quien', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deberecivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('importe', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='debetarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('cuota', models.IntegerField(null=True)),
                ('importe', models.IntegerField(null=True)),
                ('entidad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('actividad', models.CharField(max_length=50, null=True)),
                ('ingresos', models.IntegerField(null=True)),
                ('pagas', models.IntegerField(null=True)),
                ('otrosingresos', models.IntegerField(null=True)),
                ('antiguedad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='juvilacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('importe', models.IntegerField(null=True)),
                ('pagas', models.IntegerField(null=True)),
                ('fechainicio', models.DateField(null=True)),
                ('fechafin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('desdecuando', models.DateField(null=True)),
                ('cobra', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField()),
                ('avalista', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(null=True)),
                ('movil', models.IntegerField()),
                ('fechanacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('estadocivil', models.CharField(choices=[('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Pareja de hecho', 'Pareja de hecho'), ('Casado', 'Casado')], max_length=20, null=True)),
                ('tipocasado', models.CharField(choices=[('Separacion de bienes', 'Separacion de bienes'), ('Bienes gananciales', 'Bienes gananciales')], max_length=20, null=True)),
                ('numerodehijos', models.IntegerField(null=True)),
                ('sihijosmayores18', models.BooleanField(default=False)),
                ('sihijoscuantoscargo', models.IntegerField(null=True)),
                ('sihijosingreso', models.IntegerField(null=True)),
                ('justificante', models.BooleanField(default=False)),
                ('autoriza', models.BooleanField(default=False)),
                ('medio', models.CharField(choices=[('Television', 'Television'), ('Prensa', 'Prensa'), ('Radio', 'Radio'), ('Web', 'Web'), ('Publicidad Estatica', 'Publicidad Estatica'), ('Otros', 'Otros')], max_length=20, null=True)),
                ('metodopago', models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('Hal-Cash', 'Hal-Cash')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='personaanexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('seguridadsocial', models.CharField(choices=[('Propia', 'Propia'), ('Ajena', 'Ajena')], max_length=20, null=True)),
                ('siajenatipo', models.CharField(choices=[('Fijo', 'Fijo'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal')], max_length=20, null=True)),
                ('siajenatemporal', models.DateField(null=True)),
                ('otrosingresos', models.IntegerField(null=True)),
                ('otrosingresostexto', models.CharField(max_length=100, null=True)),
                ('otrosgastos', models.IntegerField(null=True)),
                ('otrosgastostexto', models.CharField(max_length=100, null=True)),
                ('importeselect1', models.IntegerField(null=True)),
                ('importeselect2', models.IntegerField(null=True)),
                ('importeselect3', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexp', models.IntegerField(null=True)),
                ('avalista', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('poblacion', models.CharField(max_length=50, null=True)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('codigopostal', models.IntegerField(null=True)),
                ('valorvivienda', models.IntegerField(null=True)),
                ('valorhipoteca', models.IntegerField(null=True)),
                ('estapagada', models.BooleanField(default=False)),
                ('sinopagadaanos', models.CharField(max_length=10, null=True)),
                ('sinopagadaentidad', models.CharField(max_length=50, null=True)),
                ('sinopagadapagahipoteca', models.IntegerField(null=True)),
                ('librecargos', models.BooleanField(default=False)),
                ('metros', models.IntegerField(null=True)),
                ('porciento', models.IntegerField(null=True)),
                ('valoralquilada', models.IntegerField(null=True)),
                ('pagaalquiler', models.IntegerField(null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
