# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debecredito',
            name='tipo',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Avalista', 'Avalista')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estadocivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Pareja de hecho', 'Pareja de hecho'), ('Casado', 'Casado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='medio',
            field=models.CharField(choices=[('Television', 'Television'), ('Prensa', 'Prensa'), ('Radio', 'Radio'), ('Web', 'Web'), ('Publicidad Estatica', 'Publicidad Estatica'), ('Otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='metodopago',
            field=models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('Hal-Cash', 'Hal-Cash')], max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipocasado',
            field=models.CharField(choices=[('Separacion de bienes', 'Separacion de bienes'), ('Bienes gananciales', 'Bienes gananciales')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='seguridadsocial',
            field=models.CharField(choices=[('Propia', 'Propia'), ('Ajena', 'Ajena')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='siajenatipo',
            field=models.CharField(choices=[('Fijo', 'Fijo'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal')], max_length=20),
        ),
    ]
