# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operadora', '0002_auto_20161220_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotaciones',
            name='destinado',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anotaciones',
            name='empresa',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anotaciones',
            name='financieros',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anotaciones',
            name='generales',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anotaciones',
            name='personales',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anotaciones',
            name='vivienda',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coches',
            name='coche',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='debecredito',
            name='cuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debecredito',
            name='entidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debecredito',
            name='importe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debecredito',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debecredito',
            name='porcientoavalista',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debecredito',
            name='tipo',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Avalista', 'Avalista')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debemoroso',
            name='importe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debemoroso',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debemoroso',
            name='quien',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deberecivos',
            name='importe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deberecivos',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debetarjeta',
            name='cuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debetarjeta',
            name='entidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debetarjeta',
            name='importe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debetarjeta',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='actividad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='antiguedad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ingresos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='otrosingresos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pagas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='juvilacion',
            name='fechafin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='juvilacion',
            name='fechainicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='juvilacion',
            name='importe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='juvilacion',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='juvilacion',
            name='pagas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paro',
            name='cobra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paro',
            name='desdecuando',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paro',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='autoriza',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estadocivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Pareja de hecho', 'Pareja de hecho'), ('Casado', 'Casado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='justificante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='medio',
            field=models.CharField(choices=[('Television', 'Television'), ('Prensa', 'Prensa'), ('Radio', 'Radio'), ('Web', 'Web'), ('Publicidad Estatica', 'Publicidad Estatica'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='metodopago',
            field=models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('Hal-Cash', 'Hal-Cash')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numerodehijos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sihijoscuantoscargo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sihijosingreso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sihijosmayores18',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipocasado',
            field=models.CharField(choices=[('Separacion de bienes', 'Separacion de bienes'), ('Bienes gananciales', 'Bienes gananciales')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='importeselect1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='importeselect2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='importeselect3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='otrosgastos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='otrosgastostexto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='otrosingresos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='otrosingresostexto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='seguridadsocial',
            field=models.CharField(choices=[('Propia', 'Propia'), ('Ajena', 'Ajena')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='siajenatemporal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personaanexos',
            name='siajenatipo',
            field=models.CharField(choices=[('Fijo', 'Fijo'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='codigopostal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='numexp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='poblacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='provincia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
