# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operadora', '0003_auto_20170105_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
